//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using WilsonORWrapper.Services;
using UserApp.Entities;

namespace UserApp.Services
{
    public partial class DepartmentService : Data<Department>
	{
		///<summary>Private constructor to force singleton.</summary>
		private DepartmentService() : base()
		{
		}
	}
}
