//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   This file is safe to edit because it will not be overwritten.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using UserApp.Entities;

namespace UserApp.Services
{
	public partial class UserService
	{
	}
}
